### ISSUE TITLE
Fixed parameters in queries

### ISSUE THREAD

**Issue by sinipessala** [jneubert/sparql-gui-gh#1]
The parameters specified in the query URL are fixed in `sparql-lab.js`. Thus, it is not possible to use new or other parameters in queries.
A general solution for parsing the parameters would be more flexible.

**Comment by jneubert** [comment]
Fixed finally by integrating code by @osma from https://github.com/NatLibFi/Finto-data/blob/master/tools/ysa-to-yso/ysa-to-yso.js, as suggested in YASGUI/YASQE#24.
